### ISSUE TITLE
XEP-0077: In-Band Registration - marked PASSED

### ISSUE THREAD

**Issue by licaon-kter** [iNPUTmice/caas#13]
ejabberd [config](https://docs.ejabberd.im/admin/configuration/#mod-register) to `prohibit usage of In-Band Registration to create or delete accounts, but allows existing accounts to change the password`:
```
access_rules:
...
  register:
    - deny
...
  mod_register:
    access: register
```

Conversations can't actually register an user.
